In [19]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import cv2
import os
import sys
import glob
import urllib.request
import json


In [3]:
file = pd.read_csv("http://ladi.s3-us-west-2.amazonaws.com/Labels/ladi_images_metadata.csv")
file

uuid            timestamp  \
0       a13fb353cca1f5e8060f95c80deb0c49e9a21f91  2016-01-16 07:34:55   
1       03e5da2bc5e32cd7d58a164eefce499e2f14e06f  2014-06-24 13:09:20   
2       c97e83122e14ec5fa5cfa6e2c911e066d8a07f7c  2014-06-24 11:06:27   
3       c534eb158948b63508eab34a667bf495e129f455  2014-06-24 11:20:03   
4       1c702459e21e5a7e7fec5eefaab42f5e5124113a  2014-06-24 11:21:07   
...                                          ...                  ...   
580746  95fabbdbbb494beab517b5fea25a4e430d8fbcef  2020-01-27 12:01:31   
580747  4b590e5634dae396db6c838844d7670e5ef9e7f6  2020-01-27 12:00:25   
580748  bb7f86f1e9ab1a1ab3ea9e13cda998ab6e1bbb6d  2020-01-27 12:02:25   
580749  c9e5c19cb7cccf181d11b707f1a47b80341710b6  2020-01-27 12:00:45   
580750  a52da08206e51e3cd3b2cd0b42a3bb7e9623e92c  2020-01-27 12:00:39   

          gps_lat    gps_lon  gps_alt  file_size   width  height  \
0       29.623744 -95.652153     26.0  3497125.0  4608.0  3456.0   
1       32.386939 -86.344467    489.0  3518243.0  4608.0  3456.0   
2             NaN        NaN      NaN  8006650.0  6000.0  4000.0   
3             NaN        NaN      NaN  8821238.0  6000.0  4000.0   
4       32.371777 -86.345887    459.0  8385536.0  6000.0  4000.0   
...           ...        ...      ...        ...     ...     ...   
580746  18.002950 -66.896370    101.8  3413576.0  4000.0  3000.0   
580747  18.003440 -66.896118    101.8  3307879.0  4000.0  3000.0   
580748  18.003280 -66.895955    101.8  3989427.0  4000.0  3000.0   
580749  18.003355 -66.896256    101.8  3722615.0  4000.0  3000.0   
580750  18.003379 -66.896208    101.8  3696682.0  4000.0  3000.0   

                                                  s3_path  \
0       s3://ladi/Images/FEMA_CAP/1012/20118/VIRB0002_...   
1       s3://ladi/Images/FEMA_CAP/1012/20118/VIRB0820_...   
2       s3://ladi/Images/FEMA_CAP/1012/20118/_DSC0015_...   
3       s3://ladi/Images/FEMA_CAP/1012/20118/_DSC0123_...   
4       s3://ladi/Images/FEMA_CAP/1012/20118/_DSC0126_...   
...                                                   ...   
580746  s3://ladi/Images/FEMA_CAP/9173/616637/2020_012...   
580747  s3://ladi/Images/FEMA_CAP/9173/616637/2020_012...   
580748  s3://ladi/Images/FEMA_CAP/9173/616637/2020_012...   
580749  s3://ladi/Images/FEMA_CAP/9173/616637/2020_012...   
580750  s3://ladi/Images/FEMA_CAP/9173/616637/2020_012...   

                                                      url  
0       https://ladi.s3-us-west-2.amazonaws.com/Images...  
1       https://ladi.s3-us-west-2.amazonaws.com/Images...  
2       https://ladi.s3-us-west-2.amazonaws.com/Images...  
3       https://ladi.s3-us-west-2.amazonaws.com/Images...  
4       https://ladi.s3-us-west-2.amazonaws.com/Images...  
...                                                   ...  
580746  https://ladi.s3-us-west-2.amazonaws.com/Images...  
580747  https://ladi.s3-us-west-2.amazonaws.com/Images...  
580748  https://ladi.s3-us-west-2.amazonaws.com/Images...  
580749  https://ladi.s3-us-west-2.amazonaws.com/Images...  
580750  https://ladi.s3-us-west-2.amazonaws.com/Images...  

[580751 rows x 10 columns]

In [10]:
file = pd.read_csv("http://ladi.s3-us-west-2.amazonaws.com/Labels/ladi_images_metadata.csv")
maas = file.loc[(file['gps_lat'] < 42.368520) & (file['gps_lat'] > 41.791453) & (file['gps_lon'] > -73.255974) &( file['gps_lon'] < - 69.998533)] 
maas
maas.to_csv('massachusetts.csv') 

In [14]:
for idx, url in enumerate(maas['url']):
    if idx<50:
        urllib.request.urlretrieve(url, 'mass/images/{}.jpg'.format(idx))


In [ ]:
# Take initial guess of intrinsic parameters through metadata
!opensfm extract_metadata mass/

# Detect features points 
!opensfm detect_features mass/

# Match feature points across images
!opensfm match_features mass/

# This creates "tracks" for the features. That is to say, if a feature in image 1 is matched with one in image 2,
# and in turn that one is matched with one in image 3, then it links the matches between 1 and 3. In this case, 
# it does not matter since we only have two images
!opensfm create_tracks mass/

# Calculates the essential matrix, the camera pose and the reconstructed feature points
!opensfm reconstruct mass/

# For visualization using Open3D
!opensfm export_ply mass/

2020-07-28 17:24:52,945 INFO: Extracting EXIF for 36.jpg
2020-07-28 17:24:53,038 INFO: Extracting EXIF for 43.jpg
2020-07-28 17:24:53,110 INFO: Extracting EXIF for 6.jpg
2020-07-28 17:24:53,239 INFO: Extracting EXIF for 49.jpg
2020-07-28 17:24:53,309 INFO: Extracting EXIF for 33.jpg
2020-07-28 17:24:53,384 INFO: Extracting EXIF for 26.jpg
2020-07-28 17:24:53,458 INFO: Extracting EXIF for 25.jpg
2020-07-28 17:24:53,536 INFO: Extracting EXIF for 8.jpg
2020-07-28 17:24:53,665 INFO: Extracting EXIF for 18.jpg
2020-07-28 17:24:53,739 INFO: Extracting EXIF for 34.jpg
2020-07-28 17:24:53,817 INFO: Extracting EXIF for 3.jpg
2020-07-28 17:24:53,931 INFO: Extracting EXIF for 38.jpg
2020-07-28 17:24:54,005 INFO: Extracting EXIF for 19.jpg
2020-07-28 17:24:54,081 INFO: Extracting EXIF for 29.jpg
2020-07-28 17:24:54,153 INFO: Extracting EXIF for 44.jpg
2020-07-28 17:24:54,225 INFO: Extracting EXIF for 24.jpg
2020-07-28 17:24:54,303 INFO: Extracting EXIF for 2.jpg
2020-07-28 17:24:54,429 INFO: Extra

In [16]:
!opensfm undistort mass/

!opensfm compute_depthmaps mass/

2020-07-28 17:29:46,675 DEBUG: Undistorting the reconstruction
2020-07-28 17:29:46,778 DEBUG: Undistorting image 4.jpg
2020-07-28 17:29:51,861 DEBUG: Undistorting image 5.jpg
2020-07-28 17:29:56,955 DEBUG: Undistorting image 3.jpg
2020-07-28 17:30:02,098 DEBUG: Undistorting image 6.jpg
2020-07-28 17:30:07,258 DEBUG: Undistorting image 7.jpg
2020-07-28 17:30:14,441 INFO: Computing neighbors
2020-07-28 17:30:14,553 INFO: Computing depthmap for image 4.jpg with PATCH_MATCH_SAMPLE
2020-07-28 17:30:34,634 INFO: Computing depthmap for image 5.jpg with PATCH_MATCH_SAMPLE
2020-07-28 17:30:56,680 INFO: Computing depthmap for image 3.jpg with PATCH_MATCH_SAMPLE
2020-07-28 17:31:13,168 INFO: Computing depthmap for image 6.jpg with PATCH_MATCH_SAMPLE
2020-07-28 17:31:33,198 INFO: Cleaning depthmap for image 4.jpg
2020-07-28 17:31:33,589 INFO: Cleaning depthmap for image 5.jpg
2020-07-28 17:31:34,068 INFO: Cleaning depthmap for image 3.jpg
2020-07-28 17:31:34,369 INFO: Cleaning depthmap for image 6

In [20]:
# Origin of our reconstruction, as given by the reference_lla.json (made from the reconstruction)
with open("mass/reference_lla.json", "r") as f:
    reference_lla = json.load(f)
    latitude=reference_lla["latitude"]
    longitude=reference_lla["longitude"]
    altitude=reference_lla["altitude"]

# This is the json file that contains the reconstructed feature points
with open("mass/reconstruction.json", "r") as f:
    reconstructions = json.load(f)

In [22]:
try:
    from pymap3d import enu2geodetic
except:
    !pip install pymap3d
    from pymap3d import enu2geodetic
from opensfm.features import denormalized_image_coordinates

# reading the csv
tracks = pd.read_csv("mass/tracks.csv", sep="\t", skiprows=1, names=["image_name", "track_id", "feature_id", "x", "y", "s", "R", "G", "B"])

# we need to denormalize the coordinates to turn them into regular pixel coordinates
normalized_coor = tracks[["x", "y", "s"]]
denormalized_coor = denormalized_image_coordinates(normalized_coor.values, 4496, 3000)

# create a new column with the denormalized coordinates
tracks["denorm_x"] = denormalized_coor[:, 0]
tracks["denorm_y"] = denormalized_coor[:, 1]

Processing /home/jovyan/.cache/pip/wheels/0c/24/19/30c440838faa979cd09d8ac37ae866669b980bfdaed4d0fb91/pymap3d-2.4.1-py3-none-any.whl


In [23]:
for reconst in reconstructions:
    for shot in reconst["shots"]:
        # some housekeeping
        shot_name = shot.split(".")[0]
        img = cv2.imread("mass/images/"+shot) 
        h,w,_ = img.shape
        
        # here we get the features from the image and their corresponding reconstructed features
        reconst_ids = list(map(int, reconst["points"].keys()))
        tracks_shot = tracks[(tracks["image_name"] == shot) & (tracks["track_id"].isin(reconst_ids))]
        
        normalized_coor = tracks_shot[["x", "y", "s"]]
        denormalized_coor = denormalized_image_coordinates(normalized_coor.values, w, h)
        
        tracks_shot["denorm_x"] = denormalized_coor[:, 0]
        tracks_shot["denorm_y"] = denormalized_coor[:, 1]
        
        denorm_shot = np.round(tracks_shot[["denorm_x", "denorm_y"]].values)
        reconst_shot = np.array([reconst["points"][str(point)]["coordinates"] for point in tracks_shot["track_id"]])
        
        # transformation for the new orthorectified image
        H, inliers = cv2.findHomography(denorm_shot, reconst_shot[:, :2],cv2.RANSAC,5.0)
        
        
        pts = np.float32([ [0,0],[0,h-1],[w-1,h-1],[w-1,0] ]).reshape(-1,1,2)
        dst = cv2.perspectiveTransform(pts,H).reshape(4, 2)
        print(pts)
                
        geo_shot = np.array([enu2geodetic(dst[i, 0],dst[i, 1],0,latitude,longitude,altitude) for i in range(dst.shape[0])])  
        print(geo_shot)

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()


[[[   0.    0.]]

 [[   0. 3999.]]

 [[5999. 3999.]]

 [[5999.    0.]]]
[[ 42.06316157 -70.68578104  22.80859427]
 [ 42.0803326  -70.63744138  23.05931396]
 [ 42.08299443 -70.64204944  21.84372186]
 [ 42.14002342 -69.9410987  357.70474123]]
[[[   0.    0.]]

 [[   0. 3999.]]

 [[5999. 3999.]]

 [[5999.    0.]]]
[[ 42.06750611 -70.69167427  21.19520673]
 [ 42.08119163 -70.64098582  22.41176614]
 [ 42.08485112 -70.64455662  21.10002777]
 [ 42.08238668 -70.8331307   18.61128792]]
[[[   0.    0.]]

 [[   0. 3999.]]

 [[5999. 3999.]]

 [[5999.    0.]]]
[[ 42.07008543 -70.658158    23.33994047]
 [ 42.07990372 -70.63508098  23.46322949]
 [ 42.08145512 -70.63994416  22.47372659]
 [ 42.03732369 -70.8997964   39.56461583]]
[[[   0.    0.]]

 [[   0. 3999.]]

 [[5999. 3999.]]

 [[5999.    0.]]]
[[ 42.07934565 -70.67640952  19.25250623]
 [ 42.08062074 -70.65132865  21.35780837]
 [ 42.08804715 -70.65393142  19.2954421 ]
 [ 42.09048038 -70.67805191  16.4618144 ]]
[[[   0.    0.]]

 [[   0. 3999.]]



In [17]:
import open3d as o3d
from open3d import JVisualizer

pcd = o3d.io.read_point_cloud("mass/reconstruction.ply")
visualizer = JVisualizer()
visualizer.add_geometry(pcd)
visualizer.show()

JVisualizer with 1 geometries